[features]
seeds = false

[programs.localnet]
perps_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
orderbook = "2XhUqeGhdkhKdZXkjHmMmFMXBJfYVVCbFxKjKqkCdMzt"
vamm = "3Vft6oJxPvHXELuqrPgCdPqJf1LxGpqDxBdqNhJxLZbm"
prop_amm = "PropAMM111111111111111111111111111111111111"
mm_registry = "MMReg11111111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/computer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
